### ISSUE TITLE
Conflicting opinion (from the author himself)

### ISSUE THREAD

**Issue by DaAwesomeP** [addyosmani/basket.js#103]
I really like this library due too its simplicity and speed, but after reading some of Chris Coyer's notes on speeding up web fonts, I stumbled upon this:

> @tkadlec @scottjehl @davatron5000 @chriscoyier local storage works if you absolutely need it, but can be slower to read than browser cache
> https://twitter.com/addyosmani/status/324610077287907328.

From the basket.js homepage:

>    Why localStorage?
> Tests by Google and Bing have shown that there are performance benefits to caching assets in localStorage (especially on mobile) <b>when compared to simply reading and writing from the standard browser cache.</b> This project is currently working on replicating these tests in the public so that we have definitive statistics on whether this is true.

So what is your <i>real</i> opinion?

**Comment by wibblymat** [comment]
I haven't looked into performance for a little while, but I remember from the last time I looked that localStorage is good:
- On mobile
- For small files

It certainly can be slower than the cache in some situations, so it isn't a panacea.
