### ISSUE TITLE
Update contributors formatting in readme

### ISSUE THREAD

**Issue by bnjmnt4n** [addyosmani/basket.js#104]
Currently, the formatting of the contributors in the README.md file seems weird. I suggest you use GitHub Flavored Markdown’s tables instead. See [here](https://raw.githubusercontent.com/bestiejs/bestiejs/master/README.md) for an example.

**Comment by sindresorhus** [comment]
Yes, that would be better. Care to do a PR?

**Comment by bnjmnt4n** [comment]
Can’t do one now, but will be able to do it next Monday :)
