### ISSUE TITLE
issue with iphone safari in traceless mode or cookie disabled

### ISSUE THREAD

**Issue by newjing** [addyosmani/basket.js#118]
In iphone safari, If I turn on traceless mode,  basket.require() will get stuck on the page.  Later on I tried normal mode but disabled cookie, the same thing happened to basket.require().   

This is weird coz disabling cookie doesn't affect basket.require() on Android. Guess iphone disables cookie & localstorage at the same time, and then when basket use localstorage it went for error.

**Comment by addyosmani** [comment]
This appears to be a more general issue with iOS cookie disabling. Without the ability to use localStorage, basket isn't going to be able to handle caching behind the scenes. If you could let me know if you were running into issues with loading completely breaking with LS off, that would be useful. Today the best answer I can offer is: we need localStorage and cookies enabled to work.
