### ISSUE TITLE
Can I use it for non-cached?

### ISSUE THREAD

**Issue by billwing** [addyosmani/basket.js#119]
Can I use `basket.js` like this `without Local Storage`:

```
basket.require({url: 'jquery.js'})
          .then(function() {
              basket.require({url: 'app.js'})
          });
```

**Comment by addyosmani** [comment]
Basket can technically be used as a standard non-cached script loader, but I would recommend using other existing options to avoid loading in the cache handler logic for users where it wouldn't actually be used for that purpose.
