### ISSUE TITLE
 Cannot retrieve scripts from some servers

### ISSUE THREAD

**Issue by the-reality-engineer** [addyosmani/basket.js#133]
```
XMLHttpRequest cannot load http://code.famo.us/famous/0.3/famous-global.min.js.
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:3000' is therefore not allowed access.
```

**Comment by addyosmani** [comment]
The exception you're seeing indicates there's a cross-domain issue caching/loading the resource. You need to ensure you're caching files on the same origin, which the browser considers a different domain (so it blocks the overall flow). Try caching the library from your own domain (for testing purposes, this would also be localhost).
