### ISSUE TITLE
any way to change the timeout?

### ISSUE THREAD

**Issue by bravocado** [addyosmani/basket.js#138]
line 259.
`timeout: 5000`

Do you have an option to change the timeout? I have a problem when i want to load the script more than 5000ms.  (which is i know, this is actually my problem because i have a script more than 500kb). But i was wondering if i can customize the timeout. :D

**Comment by Oxicode** [comment]
+1

**Comment by wibblymat** [comment]
Yes, should just be `basket.timeout = 1000000000` or whatever you need. It's global, not per-resource, though.

**Comment by bravocado** [comment]
got it. thanks @wibblymat for pointing out. :)
