### ISSUE TITLE
Performance Improvement: Direct reading/writing from/to localStorage

### ISSUE THREAD

**Issue by skilledDeveloper** [addyosmani/basket.js#140]
Using localSotrage[''] seems to be much faster than localStorage.getItem()

See these tests:
http://jsperf.com/ready-from-localstorage-string
http://jsperf.com/reading-from-localstorage

Same test with a large 64KB string:
https://jsperf.com/ready-from-localstorage-string/4

I recommend refactoring the code to improve its performance.

**Comment by sindresorhus** [comment]
This is why I wish jsperf didn't exist. It doesn't matter if Basket.js can add 1 million or 4 million entries a second. The normal use-case is to just add a few. This will have no impact whatsoever no matter how big your site is. Thanks though :)

**Comment by skilledDeveloper** [comment]
@sindresorhus Thanks for your comment. 
While I agree that the difference is not much for a few number of read/writes from/to localStorage, it doesn't hurt to choose the FASTER method over the slower method. (specially when it's a tiny code change)

**Comment by sindresorhus** [comment]
It has no effect, so it would be doing a change just for the sake of change. Also MDN recommends `.getItem`, over direct access.
