### ISSUE TITLE
is dependency on rsvp.js still required

### ISSUE THREAD

**Issue by abhijeetNmishra** [addyosmani/basket.js#146]
It seems that dependency is very minimal and can be handled easily through native Promise object or some fallback.

**Comment by seanlindo** [comment]
I tried executing the script without it and it appears this dependency is still needed. I created a gulp task to run once and forget and let NGINX serve it.

```
gulp.task('build_loader', function() {
  gulp.src(['./client/vendor/js/rsvp.min.js', './client/vendor/js/basket.min.js'])
    .pipe(concat('loader.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./public/js/helpers'));
});
```

**Comment by ray007** [comment]
Not sure about building, but looking at `basket.js` any `Promise` implementation should work with little change (RSVP.Promise -> Promise).
Any reason not to do this?
