### ISSUE TITLE
Add remove()

### ISSUE THREAD

**Issue by mahemoff** [addyosmani/basket.js#2]
A way to clear the cache would be good.

Could in theory be done manually by deleting from localStorage, but if the library encapsulates adding to localStorage, I think it should also encapsulate removing. It would allow the storage implementation to be switched too.

**Comment by miketaylr** [comment]
+1! I've seen other implementations that allow you to pass in a TTL arg and purge it if expired, etc.

**Comment by mahemoff** [comment]
Actually, what I'm keen to see (or at least discussed) is a checksum
option. If the cached version's checksum doesn't match the checksum option,
re-download it.

(I think there's merit in <script src="foo" checksum="bar" />...that would
let the browser get smart about caching scripts across domains.)

On Fri, Mar 2, 2012 at 7:26 PM, Mike Taylor <
reply@reply.github.com

> wrote:
> 
> +1! I've seen other implementations that allow you to pass in a TTL arg
> and purge it if expired, etc.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/addyosmani/basket.js/issues/2#issuecomment-4291226

## 
- Sent from my web browser

**Comment by addyosmani** [comment]
@mahemoff I've added a remove() in the latest version but I think what might be needed to meet your checksum idea above are changes to add() and require() (i.e perhaps an optional switch that if passed double checks the checksum of the version being added vs whats in cache to find out if they're different). I like @miketaylr's TTL idea but maybe that's something for a future version :)

Could we update this ticket to better reflect the checksum idea? Would like to get .remove() off the issues list if possible.

**Comment by mahemoff** [comment]
On reflection, the checksum/hash concept is primarily for the broader goal of cross-domain script sharing. A hash assertion gets over the lack-of-trust issue between different domains and is unnecessarily complex for a single-domain cache. I'd love to see basket address this in the future, as it's wasteful everyone downloading the same jquery from a hundred different domains. But same-domain is probably enough of a challenge for basket for now :).

I'm thinking the best solution might simply be a key, ie.

```
 basket
 .add('jquery-1.7.2.js, {key: 'jquery'})
 .add('app-0.0.1.js', {key: 'app'});
```

And if you want to sprinkle some magic:

```
 basket
 .add('jquery-1.7.2.js, {key: true}); // key inferred from URL to be 'jquery'
```

This of course puts the onus on the developer to rename the script URL as well as basket references to that URL whenever the script changes. (As is the common practice with cache manifests, where people include a hash or version in a comment inside cache.manifest.)

Thinking aloud here, feedback welcome!

**Comment by addyosmani** [comment]
I really like this. I think we should support the current behaviour as well as the above two cases. TTL (if we add in the future) can be just one more option,
