### ISSUE TITLE
.wait() does not wait...

### ISSUE THREAD

**Issue by peol** [addyosmani/basket.js#20]
Just noticed this, it's totally random depending on how fast your browser is (and how long the xhr takes). I simply added `setTimeout` in the `getURL` function where it adds data to `localStorage`, and the unit test fails if you `require()`, `.wait()` and check `localStorage`.

I can take a look at it when I'm finished with the custom key things (didn't want to involve this fix in that), but I would be happy if anyone would be up for tackling this issue. :)

**Comment by peol** [comment]
Here's a test that currently fails in my repo:

```
            asyncTest("require() a script, execute callback post-load via wait()", function(){
                   expect(2);
                   basket
                       .require("jquery-1.7.1.min.js")
                       .wait(function(){
                            ok(true, "callback invoked");
                            ok(
                                localStorage.getItem("basket-jquery-1.7.1.min.js"),
                                "waited correctly"
                            );
                            start();
                       });
            });
```

Wrapping the asserts in a `setTimeout` passes the test, indicating that `.wait()` doesn't actually wait, it's just been quick so we haven't noticed. :)

**Comment by addyosmani** [comment]
Good work spotting that, @peol! Depending on what our definition for .wait()'s behaviour is, it should either wait until all of the dependencies in the chain above it have resolved:

```
basket.require('jquery.js').require('underscore.js').wait( callback );
//where jquery and underscore should both be resolved before the callback is executed
```

 or until the .require() its been attached to has completed loading:

```
basket.require('jquery.js').require('underscore.js').wait( callback );
//callback executed when underscore.js has completed, but we dont care about the state of jquery
```

LabJS appears to opt for the former http://labjs.com/documentation.php#wait. Do we want to go with the same?

**Comment by peol** [comment]
Yes, that's at least what I had in mind when seeing a `wait()` function. If you want wait for individuals, we could perhaps go for something like this:

```
basket
  .require('jquery.js')
  .require('underscore.js')
  .wait({
    'jquery.js': function() {},
    'underscore.js': function() {}
  },
  // second param to .wait(), if first is an object, will invoke when all has been loaded
  function() {});
```

Without specific-callback object:

```
basket
  .require('jquery.js')
  .require('underscore.js')
  .wait(function() {
    // invoked when all has been loaded
  });
```

or simply do:

```
basket
  .require("foo.bar.js", function() {})
  .require("bar.foo.js", function() {})
  .wait(function(){});
```

I think the former is easier though.

**Comment by addyosmani** [comment]
I would say lets go for what we both expected it to do - waiting for the chain/priors to resolve/complete before executing the callback :)

**Comment by peol** [comment]
Agreed. Also, this should probably work...:

```
basket
  .wait(function() {})
  .require('jquery.js')
  .require('underscore.js');

setTimeout(function() {
  basket.wait(function() {
    // this should still be invoked..?
  });
}, 5000);
```

**Comment by addyosmani** [comment]
Just so I'm reading that correctly, would that:
- Execute the first wait() immediately
- Execute the first wait() when the rest of the chain has resolved?

All for supporting .wait() being used first in a chain, just useful to know if it was supposed to be immediate :)

**Comment by peol** [comment]
I think I'm confusing both of us. This is how I would think it works:

```
basket
  .require("foo.js")
  .require("bar.js")
  .wait(function() {})
  .require("baz.js")
  .wait(function() {});
```

First `.wait()` waits for first two.

Last `.wait()` waits for all of them.

If the user ever uses `.wait()`, it gets invoked directly if there's nothing in queue (so, basically it's working like `$(document).ready()`.

Sorry for the confusion.

**Comment by addyosmani** [comment]
No worries! Your latest example actually makes a lot of sense and I'm more than happy with us supporting this. Thanks for the clarification!

I'll be sure to get support for this documented once we land it.
