### ISSUE TITLE
Multiple files in .require()

### ISSUE THREAD

**Issue by peol** [addyosmani/basket.js#25]
So, me and Sindre discussed the possibility of pulling in several files within one `.require()`. It would look something like this:

```
basket.require({
    "foo-1.2.3.js": {
      key: "foo"
    },
    "bar-3.2.1.js": {
      key: "bar",
      overwrite: true
    }
  })
  .wait(function() {
    // use pulled-in files
  });
```

**Comment by addyosmani** [comment]
I love it! One very very minor concern: would supporting so many signature variations confuse people? Like..could/would someone use an inline callback in any of the objects passed to require in the below?

**Comment by peol** [comment]
I guess it could, we might need to streamline the API a bit if we choose to support this. If we support inline callbacks, I don't really see a reason to use .wait() for individual callbacks at all. I.e.:

```
basket
  .require('foo')
  .wait(fn)
  .require('bar')
  .require('baz')
  .wait(fn);
```

would become moot.

Maybe we should only support the `.require({})` syntax? With additional: `.require({}, <callback when all has been pulled in>)` and just ignore .wait() all together.

**Comment by sindresorhus** [comment]
We definitely should go the Python way and only have one true way of doing it.

I'm in favor of only supporting the `.require({})` syntax.

**Comment by peol** [comment]
Actually, using an object straight up might be bad, that's not guaranteed to be parsed in that order, right? So...

```
basket.require([
  {
    url: 'foo-1.2.3.js',
    key: 'foo',
    overwrite: true
  }
]).wait(fn);
```

?

**Comment by sindresorhus** [comment]
Correct, good eye. Though since we only accept one argument to require, we could drop the array, and just use infinite arguments?

`basket.require({},{},{});`

and then just `[].slice.call( arguments )`

**Comment by peol** [comment]
Yeah, that would make sense. I'll say go for that syntax. And while someone are at it, make `.add` and `.require` use the same logic behind the scenes. Or do we actually need both?

**Comment by sindresorhus** [comment]
I've also noticed there are some duplication between them, that would be nice to get fixed.

It is however useful to be able to only load a script into localStorage for later use. Preloading. But we could drop the `.add()` method and instead just have a property in our `.require()` method?

``` javascript
basket.require({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    hash: '123',
    execute: false
});
```

**Comment by addyosmani** [comment]
I actually like that suggestion. Perhaps include add() as merely a convenience method that pipes back to the below if it stays?

**Comment by sindresorhus** [comment]
We could, but I'm not sure we should, although I don't really have that strong opinion about it. We should be careful about having sugar that doesn't really save that much typing and it gives the user multiple ways to do one thing.

The point of having a powerful .require method is that they can do all the loading in one method. If we introduce the .add sugar. User will start to do this:

``` javascript
basket.add({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    hash: '123'
}).require({
    url: 'http://website.com/foo2.js',
    key: 'foo2.js',
    hash: '123'
});
```

When this, in my opinion, looks better:

``` javascript
basket.require({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    hash: '123',
    execute: false
},{
    url: 'http://website.com/foo2.js',
    key: 'foo2.js',
    hash: '123'
});
```

I'm a -0 on this.

**Comment by peol** [comment]
I think `.store()` instead of `.add()` would be a bit clearer on what the difference is, but I do agree that they'd be rather confusing at first glance.

**Comment by addyosmani** [comment]
Whilst a very very trivial note, the only reason `.add()` was named so was because people typically add things into a basket and that idea (I felt) was easy to grasp. I don't particularly mind us renaming it at all, but Sindre does raise an interesting point.

A single-use `.add()`/`.store()` probably wouldn't add that much value if we've expanded `require()` to handle most use cases. Granted than many of the most common script loaders are sticking with `.require()` in some form, I'm okay with us dropping the sugar. 

Once we've finalized the API for the next version, I'd love to get a few people actually trying out the changes so we can see whether a minimal set of methods vs. some added sugar would be needed.

**Comment by peol** [comment]
I agree, but _if_ we would have this, I thought `store` makes more sense. :)
On Mar 17, 2012 3:34 PM, "Addy Osmani" <
reply@reply.github.com>
wrote:

**Comment by sindresorhus** [comment]
> Once we've finalized the API for the next version, I'd love to get a few people actually trying out the changes so we can see whether a minimal set of methods vs. some added sugar would be needed.

Definitely. I've been thinking about this too.

**Comment by peol** [comment]
Who would be the target tho, is a solution like this implemented somewhere?
On Mar 17, 2012 9:34 PM, "Sindre Sorhus" <
reply@reply.github.com>
wrote:

**Comment by sindresorhus** [comment]
Addy knows everyone, so I'm sure he can find someone that would need this ;)

As far as I know; Google, Bing and Sencha Touch 2 uses their own localStorage loaders. The target would be devs that needs to aggressively cache their assets, like realtime sites, heavy JS apps, etc...

**Comment by addyosmani** [comment]
Not quite everyone :)

There are definitely a few people I have in mind for trying this out (including those from the Google and Facebook camps, given they've experimented in this area before). 

I'd also like to reach out to the Sencha guys and see what their thoughts are on our (relatively lightweight) approach vs. what they've done for Touch 2. The FT and one or two other large sites have been investing time in this area, so who knows? We might able to get some decent feedback when the next version is ready :)

Whilst this thread is probably not the best place for a discussion about this, I think we'll need to discuss our long-term goals for this project. It very much began as an experiment and as it evolves we'll need to decide what is left to make it truly production-ready (with a few case studies of people using it in practice etc).

**Comment by sindresorhus** [comment]
Sounds good :)

There are some stuff that needs to be done before we can consider it production ready. The first one is to get some users to try it out, give feedback, and help us create something that is intuitive and useful.

Head grab:
- Used in the wild (obviously) - and proven to be stable and pretty bug free.
- Perf tests!
- Complete test suite
- Finalized API
- Case studies
- Docs
- Superlicious website

**Comment by addyosmani** [comment]
I think that pretty much nails it!. 

With respect to the perf tests, one thing I'm going to do at the end of this weekend (or someone else can if they're free) is collect all of the relevant jsPerf performance tests related to this area (localStorage writes, vs objects etc.) and include them in a Perf section on our wiki. We currently have most of them mentioned across issues.

That can give us a starting point to defend the position that localStorage can be used for files and there are browsers where this is relatively not expensive.

**Comment by sindresorhus** [comment]
I've already collected the ones I think are useful to us in #24 btw.

**Comment by addyosmani** [comment]
Indeed you have :) I was thinking more long-term that moving them to the wiki would be useful (Im assuming we'll eventually be closing 24)

**Comment by sindresorhus** [comment]
Yes, I agree. Feel free to move them over, or I'll do it sometime ;)

**Comment by felipemorais** [comment]
Could It be closed?

**Comment by sindresorhus** [comment]
Yup
