### ISSUE TITLE
Support TTL (Time To Live) option

### ISSUE THREAD

**Issue by peol** [addyosmani/basket.js#27]
We talked about adding this, should we? It would be a nice addition perhaps. Syntax:

```
basket.add('foo-1.2.3.js', { key: 'foo', ttl: '1months' });
```

`months` in the string could be `minutes`, `hours`, `days`, `weeks`, `years` as well. Too advanced?

**EDIT:**

Implementation should be hours-only values:

``` javascript
basket.add('foo-1.2.3.s', {
  ttl: 24 * 7 // 1 week
});
```

**Comment by sindresorhus** [comment]
When would this be needed? I can't really see the usecase.

**Comment by peol** [comment]
It might be useful for some persistent caching, maybe a definition of some sort... That would need to be refreshed once a day. Iunno, I just remember someone talking about it. :)

**Comment by addyosmani** [comment]
it's worth considering further :) Would we simply be re-fetching once TTL is over? If so does that mean that the version fetched next persists with the same TTL limit (I assume so)

**Comment by peol** [comment]
Yes, exactly. One the TTL hits (on the next request) it'll just refetch and update the TTL timestamp. We can have this open for now and see when we have ironed out the "new" API if it still makes sense.

**Comment by addyosmani** [comment]
Cool. Sounds like a plan :)

**Comment by addyosmani** [comment]
Question: would there be a case where someone would want the TTL value to be a mix of weeks and days (e.g 1 week 5 days or 1 year 30 days etc?). Would that be overkill to support? (i.e `ttl: {  months: 1, days: 10  }`)

**Comment by sindresorhus** [comment]
Wouldn't it be easier if we just let the user specify the TTL in hours?

``` javascript
ttl: 24 * 7 // 1 week
```

This would save us some bloat.

**Comment by peol** [comment]
+1 on hours only and leave the math to the user.

2012/3/12 Sindre Sorhus <
reply@reply.github.com

**Comment by addyosmani** [comment]
+1 Let's roll with that :)

**Comment by addyosmani** [comment]
Just leaving this here for future reference: https://github.com/pamelafox/lscache

Pamela also approached a TTL-like solution for her project but did something interesting with trying to remove old entries automatically if you were close to exceeding the available LS space. We might want to try something like this at some point :)

**Comment by peol** [comment]
Interesting. But I think this would introduce inconsistencies in our case.
We'll focus on longer TTL:s an dropping the oldest might drop something
that still got hours, maybe even days, left. Especially if the developer
stores the TTL elsewhere for e.g. warning the user that data needs to be
refreshed soon.

But I guess it's possible to have this optional.
On Mar 17, 2012 4:54 PM, "Addy Osmani" <
reply@reply.github.com>
wrote:

**Comment by sindresorhus** [comment]
I think this would be a nice way to automagically scale the localStorage space. We should definitely consider having an opt-in for it, or even by default.

@peol I don't see the issue. Does it really matter if the cached asset is dropped to early? It will just be refetched from the server. You can't rely on it being in localStorage anyway. What if the user wipes it themselves?

The nice thing about the automatic trasher is that it will allow for new entries to take priority instead of old (and maybe even obsolete) entries. An even better use case is if the user doesn't use TTL. Then the asset would live in localStorage forever, and block new entries, but with the automatic space saving, it would be trashed when the space was needed (we would add a timeStamp on when every entry was added to localStorage).

**Comment by felipemorais** [comment]
`expire` should be renamed to `ttl` ?

What is better? remove the oldest script or who has less time to expire
I'm thinking when the script is larger than available quota...
In local tests, basket.js will remove all keys trying add the big file.

**Comment by addyosmani** [comment]
> What is better? remove the oldest script or who has less time to expire

I would say the oldest script. Removing all keys trying to add the big file is definitely something we want to avoid.

**Comment by sindresorhus** [comment]
I like `ttl`, but `expire` might be clearer.

Oldest script.

**Comment by felipemorais** [comment]
If the script is larger ( or almost larger ) than available quota. We only know after all basket.js keys were removed.

Test of localstorage limit/quota using setItem recursively, could increase performance issues.

Some idea?

**Comment by felipemorais** [comment]
what is missing to close?

**Comment by sindresorhus** [comment]
Nothing
