### ISSUE TITLE
Consolidated JS requests

### ISSUE THREAD

**Issue by thewillk** [addyosmani/basket.js#33]
Basket.js should support a way of processing consolidated JS requests.

That way, if we know that we need N JS files, then we can request them from the server and it can give us all N JS files in one response (assuming it knows the basket.js format).

I'm thinking something like:

> basket.multi({
>  "file1.js": "stuff = 123;",
>  "file2.js": "other = 456;"
> });

Making an entry point like this allows the fetch to happen over JSONP (while still working through a CDN).

I understand that this only impacts the initial load, but it might as well be fast, even when priming the local storage.

**Comment by addyosmani** [comment]
What would be the benefit of this over the server explicitly providing the N cached scripts in a concat and minified form that you just cache once? Are you effectively looking for a way to do http://...../scripts.js?get=file1.js,file2.js etc?

**Comment by thewillk** [comment]
Imagine a giant library that relies on loading only the parts you need, like YUI3.  Caching individual files would let you pick your dependancies on a per execution basis without having to spend the time executing all downloaded dependancies.

Example:
Page 1 requires libraries A, B and C
Page 2 requires libraries A, B and D

This would let page 2 get the benefit of precached libraries A and B from page 1, but it won't have the execution overhead of executing C to do it.

Two answer your second question, you would make a request for N files (probably with a URL similar to the one you mentioned), and the server would respond in a way that basket.js could split up the pieces into individually executing chunks.

**Comment by sindresorhus** [comment]
This is out of the scope of this project. The server shouldn't have to care about the frontend using basket.js.

If you need this yourself you can easily override the basket.get() method and parse the concatenated JS file yourself ;)
