### ISSUE TITLE
Clear basket.js cache

### ISSUE THREAD

**Issue by thewillk** [addyosmani/basket.js#34]
There should be a mechanism through which basket.js will remove all items under its control from local storage (i.e. all items starting with "basket-").  Otherwise, as assets change their cachebuster, basket.js will be leaky.  It should do so in a way that doesn't invalidate other parts of the local storage.

The idea is that elsewhere in the application, there's a "app version" check, and if it's incremented, then they clear basket.js.

Ideally, we'd watch for changes in the cachebuster on a per file basis, but since cachebusting is handled differently per app, this would be difficult.  On solution is that there's a mechanism to set a regex to identify where assets are the same, but just a different version.  This seems like a pita to implement and potentially buggy.  Also, it's not mutually exclusive to the "clear everything" approach.

**Comment by sindresorhus** [comment]
Clear all method is already implemented in the api-rewrite branch: https://github.com/addyosmani/basket.js/commit/4c24808d68d4f1ebfffc13ebf886974e4b0aa95b

Would that be enough?

**Comment by thewillk** [comment]
Certainly is.  My bad.

Note to self, stay off GitHub when you first wake up, or you'll end up missing something obvious.  :)
