### ISSUE TITLE
Promises reinvented

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/basket.js#45]
The `.wait()` method appears to do a very similar job to the `.then()` method on a Promises/A promise. Perhaps basket should use Promises/A compatible promises rather than a similar-but-different alternative?

**Comment by sindresorhus** [comment]
Good point.

We might explore adding a dependency on [rsvp.js](https://github.com/tildeio/rsvp.js), it's lightweight and Promises/A compliant.

What do you guys think?

**Comment by addyosmani** [comment]
Tempted to say optional dependency but it looks small enough to include by default.

**Comment by wibblymat** [comment]
I made a commit that uses https://github.com/cujojs/when rather than RSVP because RSVP doesn't have a .all() method and dumps a lot of stuff in global scope. It's a little scrappy right now but should provide a basis for discussion.

The code within basket.js gets smaller, which is nice, but adding the external library negates that.

I wasn't sure how you guys would like to deal with a dependency so I have just made a copy and put it in the repo for now for simplicity's sake.

Usage changes are:
-  use .then() instead of .wait()
-  there is no more wait attribute on the require() options object.

I updated the tests to match the new API so you can see there how it works.

**Comment by sindresorhus** [comment]
I like it :)

So there is no way to use the rsvp.js lib?

When.js is quite a bit larger. And if we were to go with a fully featured one, I think I would prefer the more popular [Q](https://github.com/kriskowal/q).

We're not going to include it in the repo, but rather add is as a dependency in the Bower component.json file.

**Comment by wibblymat** [comment]
rsvp is a little more work to handle things like calling a callback only when an array of promises are all resolved, or having functions that sometimes return values and sometimes return promises. These things aren't too difficult but are already done by when.js and Q.

For what its worth I prefer Q to when.js too but it's even bigger.

I'll change it to use rsvp see what we prefer.

**Comment by wibblymat** [comment]
That wasn't too bad - assuming there are no bugs in my allResolved function. RSVP Included in the repo because there is a bug in the current browser versions of RSVP on github. Its a simple error which breaks it completely, so I've got a fixed version in to test against.

**Comment by sindresorhus** [comment]
@wibblymat I like it :)

@addyosmani @peol u think?

> Its a simple error which breaks it completely, so I've got a fixed version in to test against.

Can you open a ticket or PR on rsvp.js to get it fixed?

**Comment by wibblymat** [comment]
@sindresorhus https://github.com/tildeio/rsvp.js/pull/26 - sorted

**Comment by peol** [comment]
Looks good to me. I'd love for us to lift out the `allResolved` function and money-patch it to `rsvp` namespace and perhaps also send a PR upstream. That'll remove some of the RSVP-specific logic from basket.js and makes it a bit more clear what we're doing.

**Comment by wibblymat** [comment]
I submitted a PR to rsvp.js (https://github.com/tildeio/rsvp.js/pull/27). I also cleaned up the code in my branch a bit 6b3abd515c89623f5aadf4d9cffdbabde97c6f3a.

**Comment by peol** [comment]
I'm cool with this when build goes through. Thanks for taking the time @wibblymat. :)

**Comment by addyosmani** [comment]
Thanks again!
