### ISSUE TITLE
Indents are effing bananas

### ISSUE THREAD

**Issue by rwaldron** [addyosmani/basket.js#5]
There are 1 space, 2 space, 3 space and 4 space indents in the source code, hard to know which is the right one.

**Comment by rwaldron** [comment]
I just found a 5 space indent.

**Comment by addyosmani** [comment]
I'm using a combination of jsBeautifier and Sublime's own tab conversion. Looks like they don't like each other!. I'll hopefully get this sorted out real soon. It is bananas. Sorry about that!
