### ISSUE TITLE
Convert site to Jekyll

### ISSUE THREAD

**Issue by sindresorhus** [addyosmani/basket.js#50]
...and docs to Markdown.

It's annoying having to write docs in HTML.

That way we can have the docs in the repo index too.

**Comment by sindresorhus** [comment]
Also add some analytics to the site.

@addyosmani Can you create an Analytics thing and add us?

**Comment by peol** [comment]
+1 on jekyll and md. Do you guys know what's supported on github pages when using jekyll (plugins and whatnot), or is just "plain" jekyll?

**Comment by sindresorhus** [comment]
Plugins are not supported at all, but that's fine, I'm pretty sure we don't need any. And if we do, we could always use JS to do it.

**Comment by sindresorhus** [comment]
Pinging you in incase any of you would be interested in doing this.

@ericduran @zenorocha

**Comment by zenorocha** [comment]
I could do that, but I really recommend [Docpad](https://github.com/bevry/docpad/) instead of Jekyll.

**Comment by sindresorhus** [comment]
@zenorocha what's the benefit? The reason I usually favor Jekyll for simple sites is because you don't have to commit the built site.

**Comment by zenorocha** [comment]
I prefer because it's made with NodeJS and they are faster on bugfixes.
But Jekyll is great too, specially because you don't have to commit the built site.

**Comment by sindresorhus** [comment]
I would use Docpad if I were to create static site anywhere else than GitHub.

**Comment by zenorocha** [comment]
Done :)

**Comment by ericduran** [comment]
Ha That was fast. :+1:

**Comment by addyosmani** [comment]
Wow. Nice work! :)
