### ISSUE TITLE
Capture documentation.md in index.html

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/basket.js#56]
Is it possible for us to better capture documentation.md in our index.html file? At the moment I feel like more folks are going to use it for reference/docs and would like to make sure it captures all the fantastic work thats been done lately.

Mat, could you look into this if you have time? We don't need to fully remove documentation.md, but for now I'd like index.html to be as up to date as it is. For 0.4, we probably want to move entirely to markdown for our docs and can just compile the index as needed.

Sound good?

Also, just make you an official collaborator on the project. Thanks so much for helping :dancer:

**Comment by addyosmani** [comment]
Maybe it would also be useful for us to somehow summarize the major changes since 0.2. e.g promises and so on near the top?

**Comment by addyosmani** [comment]
Thanks @wibblymat :)

**Comment by addyosmani** [comment]
@wibblymat is this one good to be closed?

**Comment by wibblymat** [comment]
Yes, just overlooked I think!
