### ISSUE TITLE
Upgrading from 0.2 to 0.3 will break your site

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/basket.js#58]
When I merged the updated documentation branch and then revisited the main site I got a JSON parsing error.

Version 0.2 stored the contents of the scripts directly in localStorage as a string. 0.3 stores a JSON encoded object including metadata. When basket.js 0.3 looks in localStorage and finds a script, the JSON.parse() fails on a syntax error (unless your script is coincidentally just valid JSON).

We need to somehow detect this situation and work around it.

The simplest solution seems to be to put a try/catch around the JSON.parse() and clear() the cache if we detect an error.

**Comment by addyosmani** [comment]
I ran into this yesterday but didn't get a chance to investigate further. Thanks for creating an issue @wibblymat. I definitely think we should mention this change in the changelog/readme.

I would be up for us opting for the simple solution now, but creating a separate issue to track how we can address this better in the future. Would you like to bring in a69f5c6?

**Comment by wibblymat** [comment]
Sorry, I got distracted after pushing the commit yesterday and forgot to do anything with it!

**Comment by addyosmani** [comment]
No worries! I appreciate the push. With this now in place, should we re-tag and release? Anything else left to go?

**Comment by wibblymat** [comment]
I'm not aware of anything that needs doing.

**Comment by addyosmani** [comment]
Cool. I'll retag sooooon :)
