### ISSUE TITLE
RSVP is not defined 

### ISSUE THREAD

**Issue by BeMoreDifferent** [addyosmani/basket.js#61]
Hi. 
I have this error while using basket.js: "Uncaught ReferenceError: RSVP is not defined" and "Uncaught ReferenceError: basket is not defined". How could that happen? 
has anyone an idea how to solve this issue?

Hope somebody can help
Daniel

**Comment by wibblymat** [comment]
Hi there!

basket.js now depends on the RSVP library. The repository for RSVP is https://github.com/tildeio/rsvp.js.

If you are using bower then you could also install RSVP by typing `bower install rsvp`.

Then you just need to add a script tag to load RSVP before basket.js in your HTML file.

I hope that helps get you started.

**Comment by BeMoreDifferent** [comment]
ah, ok. thanks. I thought basket.js is a standalone script. I will try it with rsvp as soon as possible :+1:
