### ISSUE TITLE
RSVP dependency is not mentioned in the documentation

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/basket.js#62]
While answering #61 I noticed that I forgot to mention RSVP. Quite important!

**Comment by addyosmani** [comment]
I think we should try to come up with a clean solution to this and I'm not opposed to doing a 0.3.x soon if it can tackle it well. 

Should we consider bundling RSVP as a part of the build if it's a hard dependency or offering a way to build it in if we're not taking care of that?. Ideally, when you download basket you shouldn't have to worry about getting anything else to work with it imo.

**Comment by peol** [comment]
I agree. I can modify the build script to spit out an
additional concatenated version later today.

**Comment by addyosmani** [comment]
Thanks Andree!

On Fri, Dec 28, 2012 at 11:13 AM, Andrée Hansson
notifications@github.comwrote:

> I agree. I can modify the build script to spit out an
> additional concatenated version later today.
> 
> On Friday, December 28, 2012, Addy Osmani wrote:
> 
> > I think we should try to come up with a clean solution to this and I'm
> > not
> > opposed to doing a 0.3.x soon if it can tackle it well.
> > 
> > Should we consider bundling RSVP as a part of the build if it's a hard
> > dependency or offering a way to build it in if we're not taking care of
> > that?. Ideally, when you download basket you shouldn't have to worry
> > about
> > getting anything else to work with it imo.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/addyosmani/basket.js/issues/62#issuecomment-11724137>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/addyosmani/basket.js/issues/62#issuecomment-11729815.

## 

_Addy Osmani_

Developer Programs Engineer at Google
Blogger at: http://addyosmani.com
Phone: +44 7771 334170

**Comment by peol** [comment]
Just merged a fix to main, there's an explanation that `basket.min.js` is a version they'll use if they want to manually handle the rsvp dependency. Closing this, please re-open if you feel that we need to explain it further/more clear.

**Comment by addyosmani** [comment]
You rock @peol! :D

**Comment by sindresorhus** [comment]
Looks succinct enough to me

**Comment by wibblymat** [comment]
:+1:
