### ISSUE TITLE
Fetch scripts immediately, even when we are executing in a specific order

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/basket.js#67]
As I mentioned in https://github.com/addyosmani/basket.js/issues/52#issuecomment-11882324 it would be good if a sequence of require().thenRequire() caused all of the scripts to begin downloading in parallel and then only _execute_ the scripts in the thenRequire once the promise for the require is fulfilled. This should give a boost to page load speeds.

**Comment by addyosmani** [comment]
+1

**Comment by sindresorhus** [comment]
:+1:

**Comment by wibblymat** [comment]
I'm not especially happy that the test I've written is sufficient but I'm not sure how best to do it. It does seem to work, though :)

**Comment by felipemorais** [comment]
@wibblemat same problem for me.

**Comment by felipemorais** [comment]
Sorry @wibblymat, I haven't seen your commit on github app. 
I like this test.
