### ISSUE TITLE
What is `defer` attr for in `execute` function?

### ISSUE THREAD

**Issue by puzrin** [addyosmani/basket.js#86]
https://github.com/addyosmani/basket.js/blob/gh-pages/lib/basket.js#L145

AFAIK, `defer` is ignored, when `src` attr missed. I'm investigating basket's code to understand, how do you guarantee, that script will be executed before promise resolve.

**Comment by wibblymat** [comment]
It's a good question! I've done a little bit of reading and it looks like it should have zero effect in any browser because we supply the text of the script, not a `src` to retrieve it from. Will try and confirm that we don't need it.
