### ISSUE TITLE
Alternate way to order init of loaded resourses

### ISSUE THREAD

**Issue by puzrin** [addyosmani/basket.js#87]
Sometime multiple dependent resourses should be loaded. Doc advices to chain loading for that case. But it would be more effective to load resourses in parallel and then inject into page in right sequence.

Here is example, implemented in my app:

``` javascript
// Storage for loaded resources;
var fetched = {};

// Replace default handler - store resourses instead of execute
// Required to inject in proper order;
basket.addHandler('default', function(obj) {
  fetched[obj.url] = obj;
});

// `resourses` is Array of urls

var res_list = [];
forEach(resources, function(url) {
  res_list.push({ url: url });
});

basket.require.apply(basket, res_list).then(function() {
  var head = document.head || document.getElementsByTagName('head')[0];
  forEach(resources, function(url) {
    loaded[url] = true;

    var obj = fetched[url];

    if (/[.]js$/.test(obj.url)) {
      var script = document.createElement('script');

      // Have to use .text, since we support IE8,
      // which won't allow appending to a script
      script.text = obj.data;
      head.appendChild(script);
      return;
    }

    if (/[.]css$/.test(obj.url)) {
      var style = document.createElement('style');

      if(style.styleSheet) style.styleSheet.cssText = obj.data; // IE method
      else style.appendChild(document.createTextNode(obj.data)); // others

      head.appendChild(style);
      return;
    }

  });
});

```

I think, that could be implemented in basket to be default action.

**Comment by wibblymat** [comment]
I'm pretty sure that if you use `thenRequire` to chain the requests it will already cause the downloads to happen in parallel. Look at the tests to see an example.

**Comment by puzrin** [comment]
`then` is called after xhr request finished, So, nested `.then(basket.require(...))` will cause sequential loading, instead of parallel.

**Comment by wibblymat** [comment]
No, I mean use `thenRequire` in you own code.

``` javascript
basket.require({url: 'urlA'})
  .thenRequire({url: 'urlB'})
  .then(whatever);
```

Both XHR requests will be made immediately but the results will be executed
in order.

**Comment by puzrin** [comment]
Ah! Found in sourses, thanks for your patience!

Well, another question - in real life, it's convenient to pass dependent resources as ordered array. Is it possible to add such signature?
