### ISSUE TITLE
Option to add script name for dev tools

### ISSUE THREAD

**Issue by puzrin** [addyosmani/basket.js#88]
Since basket scripts are inserted into page as inline code, it would be nice to add source url for debugger:

https://github.com/nodeca/nodeca.core/blob/master/assets/loader.js.ejs#L282

That can conflict with soursemap url, so, it could be an option. Or, added only if last line does not contain sourcemap info.

Don't know why, but it does not work in firefox+firebug, though works in chrome.

**Comment by addyosmani** [comment]
Certainly worth considering.

**Comment by puzrin** [comment]
Could you explain, why wrong? Having script name really helps when error happens.

**Comment by lagden** [comment]
I did an ugly stuff, but it worked...

``` javascript
// Script
basket.require({
    url     : '/js/nimble.js',
    unique  : 'nimble-v0.1.0',
    execute : false,
    key     : 'nimble'
}).then(function(){
    var req = basket.get('nimble');
    var sourceMap = '/js/nimble.js.map';
    var data = req.data.replace(/(sourceMappingURL\=)(.*)/,'$1'+sourceMap);

    var h = document.head || document.getElementsByTagName('head')[0];
    var script = document.createElement('script');
    script.defer = true;
    script.text = data;
    h.appendChild(script);
});
```

Could have an option like `sourceMapPath` in `require`
