### ISSUE TITLE
Doesn't work with latest version of RSVP

### ISSUE THREAD

**Issue by sarendipitee** [addyosmani/basket.js#91]
In  `var getUrl = function(url) {`

A promise is created like this: 

`var promise = new RSVP.Promise()`

Which immediately throws and error:

`TypeError: You must pass a resolver function as the first argument to the promise constructor`

Guessing RSVP changed their API.

**Comment by addyosmani** [comment]
From their current readme, creating a promise is done via `var promise = new RSVP.Promise(function(resolve, reject)` so we would need to update https://github.com/addyosmani/basket.js/blob/gh-pages/lib/basket.js#L48 in order for this to work again.

**Comment by addyosmani** [comment]
@JonDum btw, I don't suppose you would be interested in putting together a PR to fix this, would you? :)

**Comment by sarendipitee** [comment]
I totally would if I was using Basket, but I ended up going with something else because I didn't like Basket's syntax and I don't have the time right now to contribute to projects I'm not using sorry. :(

**Comment by addyosmani** [comment]
I've fixed this locally. Pushing the patch to master soon. The update has broken two tests that need to be resolved.
