### ISSUE TITLE
Get out a new release

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/basket.js#93]
It's been a while since we released a new version. Would love to get something out once we have docs for the latest updates in place. Perhaps also solving #91 before we publish.

Anyone opposed?

**Comment by wibblymat** [comment]
I entirely agree, I just wish I ever had time any more :/

**Comment by addyosmani** [comment]
Totally understandable @wibblymat. We'll figure out another way to get a new release out :) No worries!

Happy new year!
